In [1]:
'''Crie um array NumPy com 10 elementos inteiros aleatórios no intervalo [0, 100] e exiba os valores e o tipo de
 dado do array.
'''

import numpy as np

intervalo = np.random.randint(0,101,size = 10)
print(intervalo)
type(intervalo)

[99 62  6  1  7 14 27 27 94 25]


numpy.ndarray

In [2]:
'''Crie uma matriz de 5x5 com valores aleatórios de [0,1) e encontre o valor mínimo, máximo e a média da matriz.
'''
matriz = np.random.rand(5,5)
print(matriz)
print('mínimo:', matriz.min())
print('máximo:', matriz.max())
print('média:', matriz.std())

[[0.56827104 0.48196314 0.89821161 0.53602864 0.31670813]
 [0.27189108 0.69711421 0.6262826  0.40345822 0.17680438]
 [0.08661068 0.21566268 0.5416969  0.05791405 0.25816176]
 [0.83122789 0.50532642 0.59089815 0.20919769 0.61497676]
 [0.47905953 0.7421862  0.53599454 0.76409404 0.81274078]]
mínimo: 0.05791405058278465
máximo: 0.8982116134233001
média: 0.2338473595781709


In [6]:
'''Crie um array com 10 elementos aleatórios no intervalo [0, 1]. Em seguida, crie um novo array com os elementos 
do primeiro array multiplicados por 10 e convertidos para inteiro.
'''

variavel = np.random.rand(1,10)
variavel10 = variavel *10
print(variavel)
print(variavel10)


[[0.38767352 0.45204036 0.46859885 0.73761237 0.98833197 0.41736572
  0.8009466  0.97776269 0.25370878 0.96658561]]
[[3.8767352  4.52040364 4.6859885  7.37612367 9.88331969 4.17365718
  8.00946598 9.77762691 2.53708777 9.66585606]]


In [5]:
'''Crie um array de duas dimensões com shape (3, 3) e valores aleatórios inteiros no intervalo [0, 9]. 
Substitua todos os elementos da segunda linha por -1.
'''

import numpy as np

array = np.random.randint(0, 10, size=(3, 3))
print(array)

array[1] = -1
print(array)

[[6 7 1]
 [0 3 6]
 [7 2 6]]
[[ 6  7  1]
 [-1 -1 -1]
 [ 7  2  6]]


In [2]:
'''Crie um DataFrame com as seguintes informações:
Coluna "fruta": "Banana", "Maça", "Pera"
Coluna "preco": 7.90, 10.20, 11.80
Coluna "quantidade": 12, 3, 4
'''

import pandas as pd
pd.DataFrame({'Fruta':['banana','maça','pera'],'Preço':['7.90','10.20','11.80'],'Quantidade':[12,3,4]})

Fruta  Preço  Quantidade
0  banana   7.90          12
1    maça  10.20           3
2    pera  11.80           4